# Generated by Django 5.2.1 on 2025-08-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familydata",
            name="PersonalData",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FamilyData",
                to="form.personaldata",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="mother_lives",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                null=True,
                verbose_name="Is Alive?",
            ),
        ),
    ]
