# Generated by Django 5.2.1 on 2025-05-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recluta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=80)),
                ("apellidos", models.CharField(max_length=80)),
                (
                    "cedula",
                    models.CharField(max_length=15, unique=True, verbose_name="Cédula"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=10, unique=True)),
                (
                    "fecha_ingreso",
                    models.DateField(verbose_name="Fecha prevista de ingreso"),
                ),
                (
                    "dependencia_destino",
                    models.CharField(max_length=50, verbose_name="Dependencia"),
                ),
                ("cargo", models.CharField(max_length=80)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("INDEFINIDO", "Indefinido"),
                            ("FIJO", "Término fijo"),
                            ("PRACTICAS", "Prácticas / Aprendiz"),
                            ("OBRA", "Obra o labor"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="Identidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cc_numero", models.CharField(max_length=15)),
                ("ce_numero", models.CharField(blank=True, max_length=15)),
                ("pasaporte_numero", models.CharField(blank=True, max_length=15)),
                ("libreta_militar_numero", models.CharField(blank=True, max_length=15)),
                ("clase_libreta", models.CharField(blank=True, max_length=10)),
                ("distrito_militar", models.CharField(blank=True, max_length=20)),
                ("tarjeta_profesional", models.CharField(blank=True, max_length=30)),
                ("eps", models.CharField(max_length=50)),
                ("arl", models.CharField(max_length=50)),
                (
                    "recluta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parentesco", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=80)),
                ("identificacion", models.CharField(blank=True, max_length=20)),
                ("edad", models.PositiveIntegerField(blank=True, null=True)),
                ("cargo", models.CharField(blank=True, max_length=80)),
                ("entidad", models.CharField(blank=True, max_length=80)),
                ("telefono", models.CharField(blank=True, max_length=15)),
                (
                    "recluta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienciaLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=80)),
                ("cargo", models.CharField(max_length=80)),
                ("dependencia", models.CharField(blank=True, max_length=80)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "recluta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Educacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=80)),
                ("institucion", models.CharField(max_length=80)),
                ("ciudad", models.CharField(max_length=50)),
                ("anio", models.PositiveIntegerField()),
                (
                    "recluta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Economia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingresos_mensual", models.IntegerField()),
                ("aportantes_mensual", models.IntegerField(blank=True, null=True)),
                ("otros_ingresos_mensual", models.IntegerField(blank=True, null=True)),
                ("total_ingresos_mensual", models.IntegerField()),
                ("patrimonio_bruto", models.IntegerField()),
                ("patrimonio_neto", models.IntegerField()),
                ("total_deudas", models.IntegerField()),
                (
                    "recluta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="documentos/%Y/%m/")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "recluta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=120)),
                ("barrio", models.CharField(max_length=50)),
                ("ciudad", models.CharField(max_length=50)),
                ("departamento", models.CharField(max_length=50)),
                ("localidad", models.CharField(blank=True, max_length=50)),
                ("estrato", models.CharField(blank=True, max_length=2)),
                ("condicion_vivienda", models.CharField(max_length=30)),
                ("telefono_fijo", models.CharField(blank=True, max_length=10)),
                ("celular", models.CharField(max_length=10)),
                ("correo_personal", models.EmailField(max_length=254)),
                ("correo_institucional", models.EmailField(blank=True, max_length=254)),
                ("redes_sociales", models.CharField(blank=True, max_length=100)),
                (
                    "recluta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("ubicacion", models.CharField(max_length=100)),
                ("identificacion", models.CharField(max_length=50)),
                ("avaluo", models.IntegerField()),
                (
                    "recluta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("ocupacion", models.CharField(max_length=80)),
                ("empresa", models.CharField(max_length=80)),
                ("tiempo_conocido", models.CharField(max_length=30)),
                ("direccion", models.CharField(max_length=120)),
                ("ciudad", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=20)),
                (
                    "recluta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViajeExterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("pais", models.CharField(max_length=50)),
                ("motivo", models.CharField(max_length=100)),
                ("duracion", models.CharField(max_length=50)),
                (
                    "recluta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
    ]
