# Generated by Django 5.2.1 on 2025-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0002_alter_recluta_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="recluta",
            name="certificado_arl",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/arl/",
                verbose_name="Certificado ARL",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="certificado_eps",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/eps/",
                verbose_name="Certificado EPS",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="certificado_pension",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/pension/",
                verbose_name="Certificado Pensión",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="hv_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/hv/",
                verbose_name="Hoja de vida (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="telefono",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
