# Generated by Django 5.2.1 on 2025-05-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0003_recluta_certificado_arl_recluta_certificado_eps_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familia",
            name="telefono",
        ),
    ]
