# Generated by Django 5.2.1 on 2025-05-16 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0004_remove_familia_telefono"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recluta",
            old_name="apellidos",
            new_name="primer_apellido",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="nombres",
        ),
        migrations.AddField(
            model_name="recluta",
            name="primer_nombre",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recluta",
            name="segundo_apellido",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="recluta",
            name="segundo_nombre",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
