# Generated by Django 5.2.1 on 2025-05-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0005_rename_apellidos_recluta_primer_apellido_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recluta",
            old_name="telefono",
            new_name="numero_celular",
        ),
        migrations.AlterField(
            model_name="recluta",
            name="cedula",
            field=models.CharField(max_length=11, unique=True, verbose_name="Cédula"),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
