# Generated by Django 5.2.1 on 2025-05-16 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0006_rename_telefono_recluta_numero_celular_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recluta",
            name="cedula",
        ),
        migrations.AddField(
            model_name="recluta",
            name="numero_documento",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=11, unique=True
            ),
            preserve_default=False,
        ),
    ]
