# Generated by Django 5.2.1 on 2025-05-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0007_remove_recluta_cedula_recluta_numero_documento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recluta",
            old_name="email",
            new_name="correo_electronico",
        ),
    ]
