# Generated by Django 5.2.1 on 2025-05-16 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0008_rename_email_recluta_correo_electronico"),
    ]

    operations = [
        migrations.AddField(
            model_name="recluta",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula Ciudadanía"),
                    ("CE", "Cédula Extranjería"),
                    ("PA", "Pasaporte"),
                    ("NIT", "Número de Identificación Tributaria (NIT)"),
                ],
                default=django.utils.timezone.now,
                verbose_name="Tipo de documento",
            ),
            preserve_default=False,
        ),
    ]
