# Generated by Django 5.2.1 on 2025-05-16 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0009_recluta_tipo_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="recluta",
            name="unidad_negocio",
            field=models.CharField(
                choices=[
                    ("OC", "Oficinas Centrales"),
                    ("FEXAR", "FEXAR"),
                    ("FAGECOR", "FAGECOR"),
                    ("FASAB", "FASAB"),
                ],
                default=django.utils.timezone.now,
                verbose_name="Unidad de Negocio",
            ),
            preserve_default=False,
        ),
    ]
