# Generated by Django 5.2.1 on 2025-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0010_recluta_unidad_negocio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recluta",
            name="certificado_arl",
            field=models.FileField(
                null=True, upload_to="documentos/arl/", verbose_name="Certificado ARL"
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="certificado_eps",
            field=models.FileField(
                null=True, upload_to="documentos/eps/", verbose_name="Certificado EPS"
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="certificado_pension",
            field=models.FileField(
                null=True,
                upload_to="documentos/pension/",
                verbose_name="Certificado Pensión",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="hv_pdf",
            field=models.FileField(
                null=True, upload_to="documentos/hv/", verbose_name="Hoja de vida (PDF)"
            ),
        ),
    ]
