# Generated by Django 5.2.1 on 2025-05-16 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0011_alter_recluta_certificado_arl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recluta",
            name="fecha_expedición",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de expedición"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recluta",
            name="fecha_nacimiento",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de nacimiento"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recluta",
            name="género",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("NB", "No Binario"),
                    ("Otro", "Otro"),
                ],
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recluta",
            name="lugar_nacimiento",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
