# Generated by Django 5.2.1 on 2025-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0012_recluta_fecha_expedición_recluta_fecha_nacimiento_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recluta",
            name="unidad_negocio",
            field=models.CharField(
                choices=[
                    ("OC", "Oficinas Centrales"),
                    ("FEXAR", "FEXAR"),
                    ("FAGECOR", "FAGECOR"),
                    ("FASAB", "FASAB"),
                ],
                max_length=50,
                verbose_name="Unidad de Negocio",
            ),
        ),
    ]
