# Generated by Django 5.2.1 on 2025-05-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0013_alter_recluta_unidad_negocio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recluta",
            name="correo_electronico",
        ),
    ]
