# Generated by Django 5.2.1 on 2025-05-16 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0014_remove_recluta_correo_electronico"),
    ]

    operations = [
        migrations.AddField(
            model_name="recluta",
            name="lugar_expedición",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
