# Generated by Django 5.2.1 on 2025-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0015_recluta_lugar_expedición"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recluta",
            name="lugar_expedición",
            field=models.CharField(max_length=20, verbose_name="Lugar de expedición"),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="tipo_documento",
            field=models.CharField(
                choices=[("CC", "Cédula Ciudadanía"), ("CE", "Cédula Extranjería")],
                verbose_name="Tipo de documento",
            ),
        ),
    ]
