# Generated by Django 5.2.1 on 2025-05-19 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0016_alter_recluta_lugar_expedición_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recluta",
            name="fecha_nacimiento",
        ),
        migrations.AddField(
            model_name="recluta",
            name="año_nacimiento",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="Año de Nacimiento",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="clase_libretamilitar",
            field=models.CharField(
                choices=[
                    ("1C", "Primera Clase"),
                    ("2C", "Segunda Clase"),
                    ("Pv", "Provisional"),
                    ("Ex", "Exonerado"),
                    ("Sr", "Sin Resolver"),
                    ("N/A", "No Aplica"),
                ],
                null=True,
                verbose_name="Clase de Libreta militar",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="dia_nacimiento",
            field=models.IntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18"),
                    (19, "19"),
                    (20, "20"),
                    (21, "21"),
                    (22, "22"),
                    (23, "23"),
                    (24, "24"),
                    (25, "25"),
                    (26, "26"),
                    (27, "27"),
                    (28, "28"),
                    (29, "29"),
                    (30, "30"),
                    (31, "31"),
                ],
                null=True,
                verbose_name="Día de nacimiento",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="distrito_militar",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Distrito Militar"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="estado_civil",
            field=models.CharField(
                choices=[
                    ("Casado(a)", "Casado(a)"),
                    ("Soltero(a)", "Soltero(a)"),
                    ("Unión Marital de Hecho", "Unión Marital de Hecho"),
                    ("Separado de Hecho", "Separado de Hecho"),
                    ("Divorciado(a)", "Divorciado(a)"),
                    ("Viudo(a)", "Viudo(a)"),
                ],
                null=True,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="estatura",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(400),
                ],
                verbose_name="Estatura en centímetros",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="fecha_pasaporte",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de expedición del pasaporte"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="letra_principal",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Letra principal"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="letra_secundaria",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Letra secundaria"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="mes_nacimiento",
            field=models.CharField(
                choices=[
                    ("1", "Enero"),
                    ("2", "Febrero"),
                    ("3", "Marzo"),
                    ("4", "Abril"),
                    ("5", "Mayo"),
                    ("6", "Junio"),
                    ("7", "Julio"),
                    ("8", "Agosto"),
                    ("9", "Septiembre"),
                    ("10", "Octubre"),
                    ("11", "Noviembre"),
                    ("12", "Diciembre"),
                ],
                max_length=13,
                null=True,
                verbose_name="Mes de nacimiento",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="numero_libretamilitar",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Libreta militar No"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="numero_principal",
            field=models.CharField(
                max_length=10, null=True, verbose_name="Número principal"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="numero_secundario",
            field=models.CharField(
                max_length=10, null=True, verbose_name="Número secundario"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="pasaporte_numero",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="Pasaporte No"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="peso",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Peso en kilogramos",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="profesion_oficio",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Profesión u Oficio"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="señales_corporales",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Señales corporales"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="sobrenombres",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Sobrenombres"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="tarjeta_profesional",
            field=models.CharField(
                max_length=15,
                null=True,
                verbose_name="Código de Tarjeta profesional (Si no tiene, escriba 'N/A')",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="tipo_via",
            field=models.CharField(
                choices=[
                    ("CL", "Calle"),
                    ("CR", "Carrera"),
                    ("AV", "Avenida"),
                    ("DG", "Diagonal"),
                    ("TR", "Transversal"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de vía",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="fecha_expedición",
            field=models.DateField(verbose_name="Fecha de expedición de la cédula"),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="lugar_expedición",
            field=models.CharField(
                max_length=20, verbose_name="Lugar de expedición de la cédula"
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_documento",
            field=models.IntegerField(
                unique=True,
                verbose_name="Número de documento (sin puntos ni comas, solo números)",
            ),
        ),
    ]
