# Generated by Django 5.2.1 on 2025-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0017_remove_recluta_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recluta",
            name="bis",
            field=models.BooleanField(default=False, verbose_name="¿Bis?"),
        ),
        migrations.AddField(
            model_name="recluta",
            name="cuadrante",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTE", "ESTE"),
                    ("OESTE", "OESTE"),
                    ("NORTE", "NORTE"),
                    ("SUR", "SUR"),
                ],
                max_length=10,
                null=True,
                verbose_name="Cuadrante",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="letra_bis",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Letra Bis"
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="letra_principal",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Letra "
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="letra_secundaria",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Letra "
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_principal",
            field=models.CharField(max_length=10, null=True, verbose_name="Número "),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_secundario",
            field=models.CharField(max_length=10, null=True, verbose_name="Número "),
        ),
    ]
