# Generated by Django 5.2.1 on 2025-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0019_recluta_cuadrante_dos_recluta_espacio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recluta",
            name="direccion_formateada",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Dirección completa generada"
            ),
        ),
    ]
