# Generated by Django 5.2.1 on 2025-05-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0021_alter_recluta_letra_bis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentogenerado",
            name="creado",
        ),
    ]
