# Generated by Django 5.2.1 on 2025-05-19 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0022_remove_documentogenerado_creado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recluta",
            name="clase_libretamilitar",
            field=models.CharField(
                choices=[
                    ("1C", "Primera Clase"),
                    ("2C", "Segunda Clase"),
                    ("Pv", "Provisional"),
                    ("Ex", "Exonerado"),
                    ("Sr", "Sin Resolver"),
                    ("N/A", "No Aplica"),
                ],
                max_length=10,
                null=True,
                verbose_name="Clase de Libreta militar",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="estado_civil",
            field=models.CharField(
                choices=[
                    ("Casado(a)", "Casado(a)"),
                    ("Soltero(a)", "Soltero(a)"),
                    ("Unión Marital de Hecho", "Unión Marital de Hecho"),
                    ("Separado de Hecho", "Separado de Hecho"),
                    ("Divorciado(a)", "Divorciado(a)"),
                    ("Viudo(a)", "Viudo(a)"),
                ],
                max_length=30,
                null=True,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="estatura",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(400),
                ],
                verbose_name="Estatura (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="género",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("NB", "No Binario"),
                    ("Otro", "Otro"),
                ],
                max_length=10,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="letra_principal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=2,
                null=True,
                verbose_name="Letra",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="lugar_expedición",
            field=models.CharField(max_length=20, verbose_name="Lugar de expedición"),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="lugar_nacimiento",
            field=models.CharField(max_length=30, verbose_name="Lugar de nacimiento"),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_celular",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Número celular"
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_documento",
            field=models.IntegerField(unique=True, verbose_name="Número de documento"),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="peso",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="tarjeta_profesional",
            field=models.CharField(
                max_length=15, null=True, verbose_name="Tarjeta profesional"
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="tipo_documento",
            field=models.CharField(
                choices=[("CC", "Cédula Ciudadanía"), ("CE", "Cédula Extranjería")],
                max_length=2,
                verbose_name="Tipo de documento",
            ),
        ),
    ]
