# Generated by Django 5.2.1 on 2025-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0023_alter_recluta_clase_libretamilitar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recluta",
            name="tipo_via",
            field=models.CharField(
                choices=[
                    ("Anillo Vial", "Anillo Vial"),
                    ("Autopista", "Autopista"),
                    ("Avenida", "Avenida"),
                    ("Avenida Calle", "Avenida Calle"),
                    ("Avenida Carrera", "Avenida Carrera"),
                    ("Calle", "Calle"),
                    ("Callejón", "Callejón"),
                    ("Carrera", "Carrera"),
                    ("Circular", "Circular"),
                    ("Diagonal", "Diagonal"),
                    ("Transversal", "Transversal"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de vía",
            ),
        ),
    ]
