# Generated by Django 5.2.1 on 2025-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0024_alter_recluta_tipo_via"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recluta",
            old_name="género",
            new_name="genero",
        ),
        migrations.AddField(
            model_name="recluta",
            name="barrio",
            field=models.CharField(default=2, max_length=50, verbose_name="Barrio"),
            preserve_default=False,
        ),
    ]
