# Generated by Django 5.2.1 on 2025-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0025_rename_género_recluta_genero_recluta_barrio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recluta",
            name="numero_celular",
            field=models.IntegerField(
                max_length=13, unique=True, verbose_name="Número celular"
            ),
        ),
    ]
