# Generated by Django 5.2.1 on 2025-05-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0026_alter_recluta_numero_celular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recluta",
            name="espacio",
        ),
        migrations.AddField(
            model_name="recluta",
            name="ciudad",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Ciudad de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="correo_electronico_institucional",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Correo Electrónico Institucional",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="correo_electronico_personal",
            field=models.EmailField(
                max_length=254, null=True, verbose_name="Correo Electrónico Personal"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="departamento",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Departamento de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="facebook",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cuenta de Facebook"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cuenta de Instagram"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="nro",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Número Final"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="otras_redes",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Otras Cuentas"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="telefono_fijo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numero de teléfono fijo"
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="twitter",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cuenta de Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="ciudad",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="barrio",
            field=models.CharField(max_length=50, null=True, verbose_name="Barrio"),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_celular",
            field=models.IntegerField(
                null=True, unique=True, verbose_name="Número celular"
            ),
        ),
        migrations.CreateModel(
            name="DatosFamiliares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_conyugue",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nombre del Cónyugue"
                    ),
                ),
                (
                    "cedula_conyugue",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Cédula del Cónyugue",
                    ),
                ),
                (
                    "profesion_oficio_conyugue",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Profesión del Cónyugue",
                    ),
                ),
                (
                    "dirección_conyugue",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Dirección (texto libre)",
                    ),
                ),
                (
                    "celular_conyugue",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Celular del Cónyugue"
                    ),
                ),
                (
                    "tipo_via_conyugue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Anillo Vial", "Anillo Vial"),
                            ("Autopista", "Autopista"),
                            ("Avenida", "Avenida"),
                            ("Avenida Calle", "Avenida Calle"),
                            ("Avenida Carrera", "Avenida Carrera"),
                            ("Calle", "Calle"),
                            ("Callejón", "Callejón"),
                            ("Carrera", "Carrera"),
                            ("Circular", "Circular"),
                            ("Diagonal", "Diagonal"),
                            ("Transversal", "Transversal"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de vía",
                    ),
                ),
                (
                    "numero_principal_conyugue",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "letra_principal_conyugue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Letra",
                    ),
                ),
                (
                    "bis_conyugue",
                    models.BooleanField(default=False, verbose_name="¿Bis?"),
                ),
                (
                    "letra_bis_conyugue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Letra Bis",
                    ),
                ),
                (
                    "cuadrante_conyugue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESTE", "ESTE"),
                            ("OESTE", "OESTE"),
                            ("NORTE", "NORTE"),
                            ("SUR", "SUR"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Cuadrante",
                    ),
                ),
                (
                    "numero_secundario_conyugue",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "letra_secundaria_conyugue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Letra",
                    ),
                ),
                (
                    "cuadrante_dos_conyugue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESTE", "ESTE"),
                            ("OESTE", "OESTE"),
                            ("NORTE", "NORTE"),
                            ("SUR", "SUR"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Cuadrante",
                    ),
                ),
                (
                    "nro_conyugue",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Número Final",
                    ),
                ),
                (
                    "complemento_conyugue",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Complemento/Dirección especial",
                    ),
                ),
                (
                    "direccion_formateada_conyugue",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Dirección completa generada",
                    ),
                ),
                (
                    "recluta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.recluta",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Identidad",
        ),
    ]
