# Generated by Django 5.2.1 on 2025-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0027_remove_recluta_espacio_recluta_ciudad_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="direccion_formateada_conyugue",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="dirección_conyugue",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="direccion_formateada",
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nombre_hijo_1",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nombre_hijo_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nombre_hijo_3",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nombre_hijo_4",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nombre_hijo_5",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo"
            ),
        ),
    ]
