# Generated by Django 5.2.1 on 2025-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0028_remove_datosfamiliares_direccion_formateada_conyugue_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recluta",
            name="lugar_nacimiento",
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="edad_hijo_1",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Edad Hijo 1"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="edad_hijo_2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Edad Hijo 2"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="edad_hijo_3",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Edad Hijo 3"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="edad_hijo_4",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Edad Hijo 4"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="edad_hijo_5",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Edad Hijo 5"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="identificacion_hijo_1",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Identificación Hijo 1"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="identificacion_hijo_2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Identificación Hijo 2"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="identificacion_hijo_3",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Identificación Hijo 3"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="identificacion_hijo_4",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Identificación Hijo 4"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="identificacion_hijo_5",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Identificación Hijo 5"
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="nombre_hijo_1",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo 1"
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="nombre_hijo_2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo 2"
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="nombre_hijo_3",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo 3"
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="nombre_hijo_4",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo 4"
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="nombre_hijo_5",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre hijo 5"
            ),
        ),
    ]
