# Generated by Django 5.2.1 on 2025-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0029_remove_recluta_lugar_nacimiento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DireccionesAnteriores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion_ae",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="holaaa"
                    ),
                ),
            ],
        ),
    ]
