# Generated by Django 5.2.1 on 2025-05-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0032_direccionesanteriores_bis_anterior_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccionesanteriores",
            name="ciudad_direccion_anterior_1",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Ciudad"
            ),
        ),
        migrations.AddField(
            model_name="direccionesanteriores",
            name="ciudad_direccion_anterior_2",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Ciudad"
            ),
        ),
        migrations.AddField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_1_1",
            field=models.IntegerField(blank=True, null=True, verbose_name="Teléfono 1"),
        ),
        migrations.AddField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_1_2",
            field=models.IntegerField(blank=True, null=True, verbose_name="Teléfono 2"),
        ),
        migrations.AddField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_2_1",
            field=models.IntegerField(blank=True, null=True, verbose_name="Teléfono 1"),
        ),
        migrations.AddField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_2_2",
            field=models.IntegerField(blank=True, null=True, verbose_name="Teléfono 2"),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="numero_principal_anterior_1",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="numero_principal_anterior_2",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="numero_secundario_anterior_1",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="numero_secundario_anterior_2",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="tipo_via_anterior_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anillo Vial", "Anillo Vial"),
                    ("Autopista", "Autopista"),
                    ("Avenida", "Avenida"),
                    ("Avenida Calle", "Avenida Calle"),
                    ("Avenida Carrera", "Avenida Carrera"),
                    ("Calle", "Calle"),
                    ("Callejón", "Callejón"),
                    ("Carrera", "Carrera"),
                    ("Circular", "Circular"),
                    ("Diagonal", "Diagonal"),
                    ("Transversal", "Transversal"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de vía",
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="tipo_via_anterior_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anillo Vial", "Anillo Vial"),
                    ("Autopista", "Autopista"),
                    ("Avenida", "Avenida"),
                    ("Avenida Calle", "Avenida Calle"),
                    ("Avenida Carrera", "Avenida Carrera"),
                    ("Calle", "Calle"),
                    ("Callejón", "Callejón"),
                    ("Carrera", "Carrera"),
                    ("Circular", "Circular"),
                    ("Diagonal", "Diagonal"),
                    ("Transversal", "Transversal"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de vía",
            ),
        ),
    ]
