# Generated by Django 5.2.1 on 2025-05-21 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0033_direccionesanteriores_ciudad_direccion_anterior_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosfamiliares",
            name="edad_hijo_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Edad Hijo 1",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="edad_hijo_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Edad Hijo 2",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="edad_hijo_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Edad Hijo 3",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="edad_hijo_4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Edad Hijo 4",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="edad_hijo_5",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Edad Hijo 5",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="identificacion_hijo_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Identificación Hijo 1",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="identificacion_hijo_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Identificación Hijo 2",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="identificacion_hijo_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Identificación Hijo 3",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="identificacion_hijo_4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Identificación Hijo 4",
            ),
        ),
        migrations.AlterField(
            model_name="datosfamiliares",
            name="identificacion_hijo_5",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Identificación Hijo 5",
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_1_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Teléfono 1",
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_1_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Teléfono 2",
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_2_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Teléfono 1",
            ),
        ),
        migrations.AlterField(
            model_name="direccionesanteriores",
            name="telefono_direccion_anterior_2_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Teléfono 2",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="estatura",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(400),
                ],
                verbose_name="Estatura (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_celular",
            field=models.IntegerField(
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Número celular",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_documento",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Número de documento",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="numero_libretamilitar",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Libreta militar No",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="peso",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="recluta",
            name="telefono_fijo",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Numero de teléfono fijo",
            ),
        ),
    ]
