# Generated by Django 5.2.1 on 2025-05-21 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0034_alter_datosfamiliares_edad_hijo_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="recluta",
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="bis_padre",
            field=models.BooleanField(default=False, verbose_name="¿Bis?"),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="complemento_padre",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Complemento/Dirección especial",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="cuadrante_dos_padre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTE", "ESTE"),
                    ("OESTE", "OESTE"),
                    ("NORTE", "NORTE"),
                    ("SUR", "SUR"),
                ],
                max_length=10,
                null=True,
                verbose_name="Cuadrante",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="cuadrante_padre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTE", "ESTE"),
                    ("OESTE", "OESTE"),
                    ("NORTE", "NORTE"),
                    ("SUR", "SUR"),
                ],
                max_length=10,
                null=True,
                verbose_name="Cuadrante",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="identificación_padre",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="CC No",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="letra_bis_padre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=2,
                null=True,
                verbose_name="Letra Bis",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="letra_principal_padre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=2,
                null=True,
                verbose_name="Letra",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="letra_secundaria_padre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=2,
                null=True,
                verbose_name="Letra",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nombre_padre",
            field=models.CharField(
                max_length=55, null=True, verbose_name="Nombre del padre"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nro_padre",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Número Final"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="numero_principal_padre",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="numero_secundario_padre",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="telefono_padre",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Teléfono del Padre",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="tipo_via_padre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anillo Vial", "Anillo Vial"),
                    ("Autopista", "Autopista"),
                    ("Avenida", "Avenida"),
                    ("Avenida Calle", "Avenida Calle"),
                    ("Avenida Carrera", "Avenida Carrera"),
                    ("Calle", "Calle"),
                    ("Callejón", "Callejón"),
                    ("Carrera", "Carrera"),
                    ("Circular", "Circular"),
                    ("Diagonal", "Diagonal"),
                    ("Transversal", "Transversal"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de vía",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="vive_padre",
            field=models.CharField(
                choices=[("Sí", "Sí"), ("No", "No")], null=True, verbose_name="¿Vive?"
            ),
        ),
    ]
