# Generated by Django 5.2.1 on 2025-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0035_remove_datosfamiliares_recluta_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recluta",
            options={"verbose_name": "usuario", "verbose_name_plural": "usuarios"},
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="cargo",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="certificado_arl",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="certificado_eps",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="certificado_pension",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="creado",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="dependencia_destino",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="fecha_ingreso",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="hv_pdf",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="tipo_contrato",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="unidad_negocio",
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="oficio_profesion_padre",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Profesión u Oficio"
            ),
        ),
    ]
