# Generated by Django 5.2.1 on 2025-05-22 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0039_rename_letra_hermano_1_datosfamiliares_letra_bis_hermano_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datosfamiliares",
            name="bis_hermano_3",
            field=models.BooleanField(default=False, verbose_name="¿Bis?"),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="celular_hermano_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Celular Hermano 3",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="complemento_hermano_3",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Complemento/Dirección especial",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="cuadrante_dos_hermano_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTE", "ESTE"),
                    ("OESTE", "OESTE"),
                    ("NORTE", "NORTE"),
                    ("SUR", "SUR"),
                ],
                max_length=10,
                null=True,
                verbose_name="Cuadrante",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="cuadrante_hermano_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTE", "ESTE"),
                    ("OESTE", "OESTE"),
                    ("NORTE", "NORTE"),
                    ("SUR", "SUR"),
                ],
                max_length=10,
                null=True,
                verbose_name="Cuadrante",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="identificacion_hermano_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="Identificación Hermano 3",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="letra_bis_hermano_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=2,
                null=True,
                verbose_name="Letra Bis",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="letra_principal_hermano_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=2,
                null=True,
                verbose_name="Letra",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="letra_secundaria_hermano_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                    ("Q", "Q"),
                    ("R", "R"),
                    ("S", "S"),
                    ("T", "T"),
                    ("U", "U"),
                    ("V", "V"),
                    ("W", "W"),
                    ("X", "X"),
                    ("Y", "Y"),
                    ("Z", "Z"),
                ],
                max_length=2,
                null=True,
                verbose_name="Letra",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="nro_hermano_3",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Número Final"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="numero_principal_hermano_3",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="numero_secundario_hermano_3",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="ocupacion_hermano_3",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Ocupación Hermano 3"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="primer_apellido_hermano_3",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Primer Apellido"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="primer_nombre_hermano_3",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Primer Apellido"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="segundo_apellido_hermano_3",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Primer Apellido"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="segundo_nombre_hermano_3",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Primer Apellido"
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="tipo_via_hermano_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Anillo Vial", "Anillo Vial"),
                    ("Autopista", "Autopista"),
                    ("Avenida", "Avenida"),
                    ("Avenida Calle", "Avenida Calle"),
                    ("Avenida Carrera", "Avenida Carrera"),
                    ("Calle", "Calle"),
                    ("Callejón", "Callejón"),
                    ("Carrera", "Carrera"),
                    ("Circular", "Circular"),
                    ("Diagonal", "Diagonal"),
                    ("Transversal", "Transversal"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de vía",
            ),
        ),
    ]
