# Generated by Django 5.2.1 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0042_datosfamiliares_bis_hermano_5_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformacionAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
