# Generated by Django 5.2.1 on 2025-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0045_referenciaspersonales_bis_referencia_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorDefensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Familia",
        ),
    ]
