# Generated by Django 5.2.1 on 2025-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0047_sectordefensa_bis_sd_1_sectordefensa_bis_sd_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectordefensa",
            name="nombresyapellidos_sd_2",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Nombres y apellidos",
            ),
        ),
    ]
