# Generated by Django 5.2.1 on 2025-05-23 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0048_alter_sectordefensa_nombresyapellidos_sd_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="BienesRentasAEP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salarios_y_demas_ingresos_laborales",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999999999),
                        ],
                        verbose_name="Salarios y demás ingresos laborales",
                    ),
                ),
                (
                    "cesantías_e_intereses_de_cesantías",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999999999),
                        ],
                        verbose_name="Cesantías e intereses de cesantías",
                    ),
                ),
                (
                    "gastos_de_representación",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999999999),
                        ],
                        verbose_name="Gastos de representación",
                    ),
                ),
                (
                    "arriendos",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999999999),
                        ],
                        verbose_name="Arriendos",
                    ),
                ),
                (
                    "honorarios",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999999999),
                        ],
                        verbose_name="Honorarios",
                    ),
                ),
                (
                    "otros_ingresos_y_rentas",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999999999),
                        ],
                        verbose_name="Otros ingresos y rentas",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Educacion",
        ),
    ]
