# Generated by Django 5.2.1 on 2025-05-23 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0049_bienesrentasaep_delete_educacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bienesrentasaep",
            name="arriendos",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999),
                ],
                verbose_name="Arriendos",
            ),
        ),
        migrations.AlterField(
            model_name="bienesrentasaep",
            name="cesantías_e_intereses_de_cesantías",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999),
                ],
                verbose_name="Cesantías e intereses de cesantías",
            ),
        ),
        migrations.AlterField(
            model_name="bienesrentasaep",
            name="gastos_de_representación",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999),
                ],
                verbose_name="Gastos de representación",
            ),
        ),
        migrations.AlterField(
            model_name="bienesrentasaep",
            name="honorarios",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999),
                ],
                verbose_name="Honorarios",
            ),
        ),
        migrations.AlterField(
            model_name="bienesrentasaep",
            name="otros_ingresos_y_rentas",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999),
                ],
                verbose_name="Otros ingresos y rentas",
            ),
        ),
        migrations.AlterField(
            model_name="bienesrentasaep",
            name="salarios_y_demas_ingresos_laborales",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999),
                ],
                verbose_name="Salarios y demás ingresos laborales",
            ),
        ),
    ]
