# Generated by Django 5.2.1 on 2025-05-26 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0050_alter_bienesrentasaep_arriendos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bienesrentasaep",
            name="avaluo_comercial_bien_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Avalúo comercial del bien 1",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="avaluo_comercial_bien_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Avalúo comercial del bien 2",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="avaluo_comercial_bien_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Avalúo comercial del bien 3",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="avaluo_comercial_bien_4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Avalúo comercial del bien 4",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="avaluo_comercial_bien_5",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Avalúo comercial del bien 5",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="calidad_de_miembro_1",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Calidad de miembro 1",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="calidad_de_miembro_2",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Calidad de miembro 2",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="calidad_de_miembro_3",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Calidad de miembro 3",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="calidad_de_miembro_4",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Calidad de miembro 4",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="calidad_de_miembro_AEP_1",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Calidad de miembro 1",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="calidad_de_miembro_AEP_2",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Calidad de miembro 2",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="calidad_de_miembro_AEP_3",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Calidad de miembro 3",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="concepto_obligacion_1",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Concepto"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="concepto_obligacion_2",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Concepto"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="concepto_obligacion_3",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Concepto"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="concepto_obligacion_4",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Concepto"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="empresa_1",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Empresa 1"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="empresa_2",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Empresa 2"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="empresa_3",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Empresa 3"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_financiera_1",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Entidad Financiera 1",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_financiera_2",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Entidad Financiera 2",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_financiera_3",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Entidad Financiera 3",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_financiera_4",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Entidad Financiera 4",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_financiera_5",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Entidad Financiera 5",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_financiera_6",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Entidad Financiera 6",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_institucion_1",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Entidad o institución 1",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_institucion_2",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Entidad o institución 2",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_institucion_3",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Entidad o institución 3",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_institucion_4",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Entidad o institución 4 ",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_persona_obligacion_1",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Entidad o persona"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_persona_obligacion_2",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Entidad o persona"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_persona_obligacion_3",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Entidad o persona"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="entidad_o_persona_obligacion_4",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Entidad o persona"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="identificacion_bien_1",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Identificación del bien 1",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="identificacion_bien_2",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Identificación del bien 2",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="identificacion_bien_3",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Identificación del bien 3",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="identificacion_bien_4",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Identificación del bien 4",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="identificacion_bien_5",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Identificación del bien 5",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="numero_de_cuenta_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Numero de cuenta 1",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="numero_de_cuenta_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Numero de cuenta 2",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="numero_de_cuenta_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Numero de cuenta 3",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="numero_de_cuenta_4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Numero de cuenta 4",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="numero_de_cuenta_5",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Numero de cuenta 5",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="numero_de_cuenta_6",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Numero de cuenta 6",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_bien_1",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Tipo de bien 1"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_bien_2",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Tipo de bien 2"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_bien_3",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Tipo de bien 3"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_bien_4",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Tipo de bien 4"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_bien_5",
            field=models.CharField(
                blank=True, max_length=333, null=True, verbose_name="Tipo de bien 5"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_de_cuenta_1",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Tipo de cuenta 1"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_de_cuenta_2",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Tipo de cuenta 2"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_de_cuenta_3",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Tipo de cuenta 3"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_de_cuenta_4",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Tipo de cuenta 4"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_de_cuenta_5",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Tipo de cuenta 5"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="tipo_de_cuenta_6",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Tipo de cuenta 6"
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="ubicacion_bien_1",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Ubicación del bien 1 (Ciudad)",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="ubicacion_bien_2",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Ubicación del bien 2 (Ciudad)",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="ubicacion_bien_3",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Ubicación del bien 3 (Ciudad)",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="ubicacion_bien_4",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Ubicación del bien 4 (Ciudad)",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="ubicacion_bien_5",
            field=models.CharField(
                blank=True,
                max_length=333,
                null=True,
                verbose_name="Ubicación del bien 5 (Ciudad)",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="valor_1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="valor_2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="valor_3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="valor_4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999999999),
                ],
                verbose_name="Valor",
            ),
        ),
    ]
