# Generated by Django 5.2.1 on 2025-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0051_bienesrentasaep_avaluo_comercial_bien_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SituacionJuridica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_proceso_1",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Proceso 1"
                    ),
                ),
                (
                    "tipo_de_investigacion_1",
                    models.CharField(
                        blank=True,
                        max_length=333,
                        null=True,
                        verbose_name="Tipo de Investigación 1",
                    ),
                ),
                (
                    "causa_1",
                    models.CharField(
                        blank=True, max_length=333, null=True, verbose_name="Causa 1"
                    ),
                ),
                (
                    "autoridad_1",
                    models.CharField(
                        blank=True,
                        max_length=333,
                        null=True,
                        verbose_name="Autoridad 1",
                    ),
                ),
                (
                    "estado_del_proceso_1",
                    models.CharField(
                        blank=True,
                        max_length=333,
                        null=True,
                        verbose_name="Estado del Proceso 1",
                    ),
                ),
                (
                    "responsable_1",
                    models.CharField(
                        blank=True,
                        choices=[("Sí", "Sí"), ("No", "No")],
                        max_length=333,
                        null=True,
                        verbose_name="¿Responsable?",
                    ),
                ),
                (
                    "fecha_proceso_2",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Proceso 2"
                    ),
                ),
                (
                    "tipo_de_investigacion_2",
                    models.CharField(
                        blank=True,
                        max_length=333,
                        null=True,
                        verbose_name="Tipo de Investigación 2",
                    ),
                ),
                (
                    "causa_2",
                    models.CharField(
                        blank=True, max_length=333, null=True, verbose_name="Causa 2"
                    ),
                ),
                (
                    "autoridad_2",
                    models.CharField(
                        blank=True,
                        max_length=333,
                        null=True,
                        verbose_name="Autoridad 2",
                    ),
                ),
                (
                    "estado_del_proceso_2",
                    models.CharField(
                        blank=True,
                        max_length=333,
                        null=True,
                        verbose_name="Estado del Proceso 2",
                    ),
                ),
                (
                    "responsable_2",
                    models.CharField(
                        blank=True,
                        choices=[("Sí", "Sí"), ("No", "No")],
                        max_length=333,
                        null=True,
                        verbose_name="¿Responsable?",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExperienciaLaboral",
        ),
    ]
