# Generated by Django 5.2.1 on 2025-05-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0053_otrosdatos_remove_referencia_recluta_delete_economia_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viajeexterior",
            name="recluta",
        ),
        migrations.DeleteModel(
            name="Bien",
        ),
        migrations.DeleteModel(
            name="ViajeExterior",
        ),
    ]
