# Generated by Django 5.2.1 on 2025-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0055_alter_bienesrentasaep_arriendos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccionesanteriores",
            name="direccion_completa_anterior_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="direccionesanteriores",
            name="direccion_completa_anterior_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
