# Generated by Django 5.2.1 on 2025-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0056_direccionesanteriores_direccion_completa_anterior_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="referenciaspersonales",
            name="direccion_preview_referencia_1",
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AddField(
            model_name="referenciaspersonales",
            name="direccion_preview_referencia_2",
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AddField(
            model_name="referenciaspersonales",
            name="direccion_preview_referencia_3",
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
    ]
