# Generated by Django 5.2.1 on 2025-05-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0057_referenciaspersonales_direccion_preview_referencia_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bienesrentasaep",
            options={
                "verbose_name": "Bienes y Rentas AEP",
                "verbose_name_plural": "Bienes y Rentas AEP",
            },
        ),
        migrations.AlterModelOptions(
            name="datosfamiliares",
            options={
                "verbose_name": "Dato Familiar",
                "verbose_name_plural": "Datos Familiares",
            },
        ),
        migrations.AlterModelOptions(
            name="direccionesanteriores",
            options={
                "verbose_name": "Dirección Anterior",
                "verbose_name_plural": "Direcciones Anteriores",
            },
        ),
        migrations.AlterModelOptions(
            name="informacionacademica",
            options={
                "verbose_name": "Información Académica",
                "verbose_name_plural": "Informaciones Académicas",
            },
        ),
        migrations.AlterModelOptions(
            name="otrosdatos",
            options={
                "verbose_name": "Otros Datos",
                "verbose_name_plural": "Otros Datos",
            },
        ),
        migrations.AlterModelOptions(
            name="recluta",
            options={"verbose_name": "Recluta", "verbose_name_plural": "Reclutas"},
        ),
        migrations.AlterModelOptions(
            name="referenciaspersonales",
            options={
                "verbose_name": "Referencias Personales",
                "verbose_name_plural": "Referencias Personales",
            },
        ),
        migrations.AlterModelOptions(
            name="sectordefensa",
            options={
                "verbose_name": "Sector Defensa",
                "verbose_name_plural": "Sector Defensa",
            },
        ),
        migrations.AddField(
            model_name="bienesrentasaep",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bienes_rentas",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datos_familiares",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="direccionesanteriores",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direcciones_anteriores",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="informacionacademica",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="informaciones_academicas",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="otrosdatos",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otros_datos",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="recluta",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nombre_relacion",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="referenciaspersonales",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referencias_personales",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="sectordefensa",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sector_defensa",
                to="formulario.recluta",
            ),
        ),
        migrations.AddField(
            model_name="situacionjuridica",
            name="recluta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="situaciones_juridicas",
                to="formulario.recluta",
            ),
        ),
    ]
