# Generated by Django 5.2.1 on 2025-05-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0058_alter_bienesrentasaep_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referenciaspersonales",
            name="direccion_preview_referencia_1",
        ),
        migrations.RemoveField(
            model_name="referenciaspersonales",
            name="direccion_preview_referencia_2",
        ),
        migrations.RemoveField(
            model_name="referenciaspersonales",
            name="direccion_preview_referencia_3",
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_conyugue",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_hermano_1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_hermano_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_hermano_3",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_hermano_4",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_hermano_5",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_madre",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="datosfamiliares",
            name="direccion_formateada_padre",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="otrosdatos",
            name="direccion_formateada_recomendante",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recluta",
            name="direccion_formateada",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="referenciaspersonales",
            name="direccion_formateada_referencia_1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="referenciaspersonales",
            name="direccion_formateada_referencia_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="referenciaspersonales",
            name="direccion_formateada_referencia_3",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sectordefensa",
            name="direccion_formateada_sd_1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sectordefensa",
            name="direccion_formateada_sd_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
