# Generated by Django 5.2.1 on 2025-05-29 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0059_remove_referenciaspersonales_direccion_preview_referencia_1_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="edad_hijo_1",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="edad_hijo_2",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="edad_hijo_3",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="edad_hijo_4",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="edad_hijo_5",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="identificacion_hijo_1",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="identificacion_hijo_2",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="identificacion_hijo_3",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="identificacion_hijo_4",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="identificacion_hijo_5",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="nombre_hijo_1",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="nombre_hijo_2",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="nombre_hijo_3",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="nombre_hijo_4",
        ),
        migrations.RemoveField(
            model_name="datosfamiliares",
            name="nombre_hijo_5",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="recluta",
        ),
        migrations.CreateModel(
            name="Hijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del hijo"),
                ),
                (
                    "edad",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Edad",
                    ),
                ),
                (
                    "identificacion",
                    models.CharField(max_length=20, verbose_name="Identificación"),
                ),
                (
                    "datos_familiares",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="formulario.datosfamiliares",
                    ),
                ),
            ],
        ),
    ]
