# Generated by Django 5.2.1 on 2025-06-03 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0061_alter_datosfamiliares_recluta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hermano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primer_apellido_hermano",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Primer Apellido",
                    ),
                ),
                (
                    "segundo_apellido_hermano",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Segundo Apellido",
                    ),
                ),
                (
                    "primer_nombre_hermano",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Primer Nombre",
                    ),
                ),
                (
                    "segundo_nombre_hermano",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Segundo Nombre",
                    ),
                ),
                (
                    "identificacion_hermano",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(99999999999),
                        ],
                        verbose_name="Identificación Hermano 1",
                    ),
                ),
                (
                    "ocupacion_hermano",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Ocupación Hermano 1",
                    ),
                ),
                (
                    "celular_hermano",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(99999999999),
                        ],
                        verbose_name="Celular Hermano 1",
                    ),
                ),
                (
                    "tipo_via_hermano",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Anillo Vial", "Anillo Vial"),
                            ("Autopista", "Autopista"),
                            ("Avenida", "Avenida"),
                            ("Avenida Calle", "Avenida Calle"),
                            ("Avenida Carrera", "Avenida Carrera"),
                            ("Calle", "Calle"),
                            ("Callejón", "Callejón"),
                            ("Carrera", "Carrera"),
                            ("Circular", "Circular"),
                            ("Diagonal", "Diagonal"),
                            ("Transversal", "Transversal"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de vía",
                    ),
                ),
                (
                    "numero_principal_hermano",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "letra_principal_hermano",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Letra",
                    ),
                ),
                (
                    "bis_hermano",
                    models.BooleanField(default=False, verbose_name="¿Bis?"),
                ),
                (
                    "letra_bis_hermano",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Letra Bis",
                    ),
                ),
                (
                    "cuadrante_hermano",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESTE", "ESTE"),
                            ("OESTE", "OESTE"),
                            ("NORTE", "NORTE"),
                            ("SUR", "SUR"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Cuadrante",
                    ),
                ),
                (
                    "numero_secundario_hermano",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "letra_secundaria_hermano",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Letra",
                    ),
                ),
                (
                    "cuadrante_dos_hermano",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESTE", "ESTE"),
                            ("OESTE", "OESTE"),
                            ("NORTE", "NORTE"),
                            ("SUR", "SUR"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Cuadrante",
                    ),
                ),
                (
                    "nro_hermano",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Número Final",
                    ),
                ),
                (
                    "complemento_hermano",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Complemento/Dirección especial",
                    ),
                ),
                (
                    "direccion_formateada_hermano",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "datos_familiares",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hermanos",
                        to="formulario.datosfamiliares",
                    ),
                ),
            ],
        ),
    ]
