# Generated by Django 5.2.1 on 2025-07-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0065_remove_recluta_distrito_militar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recluta",
            name="clase_libretamilitar",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="numero_libretamilitar",
        ),
    ]
