# Generated by Django 5.2.1 on 2025-07-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0066_remove_recluta_clase_libretamilitar_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DireccionesAnteriores",
        ),
    ]
