# Generated by Django 5.2.1 on 2025-07-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0067_delete_direccionesanteriores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informacionacademica",
            name="año_estudios_3",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="año_estudios_4",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="ciudad_estudios_3",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="ciudad_estudios_4",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="estudios_3",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="estudios_4",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="nombre_institucion_estudios_3",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="nombre_institucion_estudios_4",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="titulo_estudios_3",
        ),
        migrations.RemoveField(
            model_name="informacionacademica",
            name="titulo_estudios_4",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="correo_electronico_institucional",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="otras_redes",
        ),
        migrations.RemoveField(
            model_name="recluta",
            name="twitter",
        ),
    ]
