# Generated by Django 5.2.1 on 2025-07-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0069_remove_bienesrentasaep_avaluo_comercial_bien_3_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OtrosDatos",
        ),
    ]
