# Generated by Django 5.2.1 on 2025-07-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0070_delete_otrosdatos"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SectorDefensa",
        ),
    ]
