# Generated by Django 5.2.1 on 2025-07-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0071_delete_sectordefensa"),
    ]

    operations = []
