# Generated by Django 5.2.1 on 2025-07-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0072_rename_recluta_to_personaldata"),
    ]

    operations = []
